### PR TITLE
Add wasm build

### PR DESCRIPTION
**Pull request by sparkprime**
@sbarzowski @buremba please take a look

This is inspired by the code @buremba posted in #295

I have another modification in the C++ repo that makes the website use this instead of the emscripten build and it seems to work...

### CODE REVIEW

**Comment by sparkprime** [comment]
The website change is https://github.com/google/jsonnet/pull/940

**Comment by sparkprime** [comment]
We might have to disable the wasm build in tests or something

**Comment by sbarzowski** [comment]
Cool stuff. We need to resolve the build error, though. Perhaps it's enough to add build constraints to `cmd/wasm/main.go`?  Right now it's complaining, because it tries to build stuff for linux and we're asking to import `syscall/js`.

**Comment by sparkprime** [comment]
Yes you have to use GOOS=js GOARCH=wasm to compile a go file that imports syscall/js.

So, clearly we don't want to build it as part of our regular stuff.  But we probably do want to build it as standard just to test for compilation errors (tests would be good too but not sure how to achieve that without a JS test framework which might be overkill).

**Comment by sparkprime** [comment]
Does it need something for bazel too?

**Comment by sparkprime** [comment]
Hmm go1.11.x seems not to support it:
```
+ go build -o libjsonnet.wasm ./cmd/wasm
# github.com/google/go-jsonnet/cmd/wasm
cmd/wasm/main.go:63:48: p[2].JSValue undefined (type js.Value has no field or method JSValue)
cmd/wasm/main.go:67:52: p[3].JSValue undefined (type js.Value has no field or method JSValue)
cmd/wasm/main.go:71:54: p[4].JSValue undefined (type js.Value has no field or method JSValue)
cmd/wasm/main.go:75:52: p[5].JSValue undefined (type js.Value has no field or method JSValue)
cmd/wasm/main.go:79:54: p[6].JSValue undefined (type js.Value has no field or method JSValue)
cmd/wasm/main.go:121:83: undefined: js.Func
cmd/wasm/main.go:122:9: undefined: js.FuncOf
cmd/wasm/main.go:123:41: undefined: js.FuncOf
note: module requires Go 1.13make: *** [Makefile:45: test] Error 2
```

**Comment by sparkprime** [comment]
@sbarzowski Good to go now?

**Pull request merged**
