### PR TITLE
Add support for missing functions in C-bindings.

### PR DESCRIPTION
**Pull request by sbarzowski**
With this change we cover 100% of the C API.

### CODE REVIEW

**Comment by sbarzowski** [comment]
@alldroll @ramaro @sparkprime

**Comment by sbarzowski** [comment]
(After this change they should also work with Python bindings).

**Comment by alldroll** [comment]
LGTM!

Could you please describe why is [it](https://github.com/google/go-jsonnet/pull/466/files#diff-d239e67b7d1d363de0b39f18b145f425b4ddc093e59304d55cc5c86d592e6c47R249) a concern for you?

**Comment by sbarzowski** [comment]
Thanks. The concern was about how it's supposed to be freed. I verified that it's supposed to be freed using jsonnet_realloc (that's what the comments in libjsonnet.h require) which results in it being freed with `free` and that's what memory allocated with `C.Cstring` expects, so we're good.

**Pull request merged**
