### PR TITLE
Efficient native implementation of std.join

### PR DESCRIPTION
**Pull request by sbarzowski**
It changes the behavior slightly - mixing strings
and arrays in join is no longer allowed.

### CODE REVIEW

**Comment by sbarzowski** [comment]
.

**Comment by sbarzowski** [comment]
@sparkprime @lwander

**Comment by sparkprime** [comment]
Changing the behavior is OK.  I don't think one can consider this as useful behavior:

```
$ jsonnet -e 'std.join([],[[1],"2",[3]])'
"[1]2[ ][3]"
```

**Comment by sparkprime** [comment]
I haven't forgotten this btw, I just want to make the incompatible change to both sides simultaneously.

**Comment by sbarzowski** [comment]
FYI I have started working on doing the same thing in C++. I got a bit stuck, though, debugging replacing a frame in a builtin.

**Comment by sparkprime** [comment]
I've changed my mind about doing performance optimizations on both sides. I think we need to encourage people to switch over so let's focus our efforts here.

**Pull request merged**
