### PR TITLE
Make jsonnetfmt add plus objects instead of removing them

### PR DESCRIPTION
**Pull request by curusarn**
Implements: https://github.com/google/go-jsonnet/issues/496

- I reused the `fix_plus_sign.go` file instead of removing it and creating a new one. Let me know if you would like rename it.
- I don't add new `Fodder` nor interact with existing `Fodder` in any way. I think that is correct but that's for someone more knowledgeable to say.
- I'm not sure if the comments are correct so please check them.

### CODE REVIEW

**Comment by sbarzowski** [comment]
This modification should be behind a new option flag. You can leave the old FixPlusObject as it was and copy the new version with a different name. Perhaps you can also rename the old one, so they're both more specific. 

Regarding fodder, I think we're good, but we should add a test for that anyway. A good test would be to have implicit + with as many comments as possible. E.g. `/* a */ { /* b */ foo: /* c */ 1 /* d */ } /* e */ { /* f */ foo: /* g */ 2 /* h */ } /* i */`. If the output doesn't lose or move any comments weirdly, we're good.

**Comment by sbarzowski** [comment]
Ah, it seems that for formatter, we're depending completely on cpp-jsonnet test suite. Hmmm... Let's just test it manually for now and I'll think what we can do about it.

**Comment by curusarn** [comment]
> This modification should be behind a new option flag. 

Ah, I see. I got an impression that @seh suggested that adding plus objects could be the new default behavior.

**Comment by seh** [comment]
I'd prefer that that become the default, but I defer to @sbarzowski to decide whether we can afford the change in the golden test files.

**Comment by sbarzowski** [comment]
It might become the default later, but let's not get ahead of ourselves :-).

**Comment by curusarn** [comment]
I suppose that no matter what the default is we still want to have an option for the other behavior. So I will change the PR to add an option for the new behavior.

**Comment by curusarn** [comment]
Do you have an idea for how the command-line option should be named? Perhaps `--[no-]use-implicit-plus` or
`--[no-]forbid-implicit-plus`?

**Comment by sbarzowski** [comment]
I like `--[no-]use-implicit-plus`.

**Comment by curusarn** [comment]
@sbarzowski Can you point me to the test files for the formatter? I found testdata and I assume it is used by linter, formatter, and parser. But I don't know how exactly.

**Comment by curusarn** [comment]
If there are some docs about it just point me there. I don't want to waste your time.

**Comment by sbarzowski** [comment]
The formatter is tested only using cpp-jsonnet test suite. We are interested in "cmd" tests (b/c we're not changing the output with default settings). Here they are: https://github.com/google/jsonnet/blob/v0.17.0/test_cmd/run_cmd_tests.sh. If you run into any trouble feel free to leave it out and I'll do it myself.

**Comment by curusarn** [comment]
Here is a diff with test for `--no-use-implicit-plus`:
```diff
diff --git a/test_cmd/fmt_no_use_implicit_plus.golden.stdout.golang b/test_cmd/fmt_no_use_implicit_plus.golden.stdout.golang
new file mode 100644
index 0000000..3d46393
--- /dev/null
+++ b/test_cmd/fmt_no_use_implicit_plus.golden.stdout.golang
@@ -0,0 +1,5 @@
+[
+  /* a */
+  { /* b */ foo: /* c */ 1 /* d */ } + /* e */
+  { /* f */ foo: /* g */ 2 /* h */ }, /* i */
+]
diff --git a/test_cmd/fmt_no_use_implicit_plus.stdin b/test_cmd/fmt_no_use_implicit_plus.stdin
new file mode 100644
index 0000000..0332273
--- /dev/null
+++ b/test_cmd/fmt_no_use_implicit_plus.stdin
@@ -0,0 +1,4 @@
+[
+  /* a */ { /* b */ foo: /* c */ 1 /* d */ } /* e */
+  { /* f */ foo: /* g */ 2 /* h */ } /* i */
+]
diff --git a/test_cmd/run_cmd_tests.sh b/test_cmd/run_cmd_tests.sh
index 9d9086f..2703ec5 100755
--- a/test_cmd/run_cmd_tests.sh
+++ b/test_cmd/run_cmd_tests.sh
@@ -128,6 +128,7 @@ if do_fmt_test "fmt_out" 0 -e "{ a: 1, b: 2, c: 3 }" -o "out/fmt_out/custom_outp
     check_file "fmt_out" "out/fmt_out/custom_output" "fmt_out.golden.custom_output"
 fi
 do_fmt_test "fmt_double_dash" 0 -e -- -1
+do_fmt_test "fmt_no_use_implicit_plus" 0 --no-use-implicit-plus
 
 if mkdir -p "out/fmt_inplace" && cp "test.jsonnet" "out/fmt_inplace/test.jsonnet"; then
     # Test jsonnetfmt in-place modifications
```

Is this okay? Should I create a separate PR in `google/jsonnet` or can you just apply the diff?

I tried running the tests and I encountered some issues. I didn't figure out how to refresh existing golden files for jsonnetfmt (jsonnetfmt --help doesn't match).

**Comment by sbarzowski** [comment]
It's fine. I'll apply the change on the cpp-jsonnet side. So, it seems the only thing that we're still missing here is the CLA.

**Comment by curusarn** [comment]
I have passed the CLA to my employer's legal department. I will need to wait for them to review it and sign it. Not sure how long that is going to take.

**Comment by curusarn** [comment]
@googlebot I signed it!

**Comment by curusarn** [comment]
@sbarzowski I don't mean to urge you. I'm just pinging you to let you know that everything should be ready.

**Comment by sbarzowski** [comment]
Thank you for the reminder! Generally feel free to ping on issues and especially PRs when they're taking too long.

I can't promise that I will always reply quickly (in the recent weeks I had ~0 free capacity).

**Pull request merged**
