### PR TITLE
Adds TravisCI release process

### PR DESCRIPTION
**Pull request by lwander**
Given the <tag> chosen in the GitHub releases page, this builds jsonnet
for darwin & linux amd64 (we can add more if needed), and uploads to
`gs://jsonnet/<tag>/<os>/<arch>/jsonnet`

### CODE REVIEW

**Comment by lwander** [comment]
It looks like I'm unable to encrypt the json key using the travis gem... maybe a lack of permissions in this repo? @sparkprime

**Comment by lwander** [comment]
Turns out the key can only be decrypted during during a release -- should be good to go now.

**Comment by sparkprime** [comment]
Should we kick it off for the last few previous releases somehow?

**Comment by lwander** [comment]
I think GH releases allows you to re-tag prior releases. If that's possible, I would run it.

**Pull request merged**
