### PR TITLE
feat: Add missing linter metadata for std.manifestTomlEx function

### LINKED ISSUE #587: Linter finding issues with std.manifestTomlEx
`jsonnet-lint` has issues with `std.manifestTomlEx` which was recently added to the standard library.

### PR DESCRIPTION
**Pull request by jaymebrd**
Fixes #587

### CODE REVIEW

**Comment by m-messiah** [comment]
@sparkprime can you check this, please? 1.18.0 is not fully supported in the linter

**Comment by m-messiah** [comment]
Hello! Could we proceed with it?

**Comment by sbarzowski** [comment]
Sorry for the delay and thank you!

**Comment by christopherhein** [comment]
THANK YOU!

**Comment by jaymebrd** [comment]
FYI @m-messiah and @christopherhein you might be interested in this change https://github.com/google/go-jsonnet/pull/637 which significantly improved toml rendering, it's released with the latest go-jsonnet.

**Comment by christopherhein** [comment]
Fantastic, thanks!

**Pull request merged**
