### PR TITLE
Fix strip definition

### PR DESCRIPTION
**Pull request by isarrigiannis**
Add missing first parameter: the string to be stripped

### CODE REVIEW

**Comment by sbarzowski** [comment]
Ah. Could you add the appropriate regression test to this file: https://github.com/google/go-jsonnet/blob/master/testdata/stdlib_smoke_test.jsonnet? See the comment on top for instructions.

To regenerate the output, use `go test ./... -update` in the root directory. Then inspect the diff to make sure there is no unexpected output (e.g. lines in the linter output).

**Comment by fenech** [comment]
@googlebot I fixed it.

**Comment by fenech** [comment]
@googlebot I consent.

**Comment by sbarzowski** [comment]
Yes, thank you!

**Pull request merged**
