### PR TITLE
Automatically create output folders

### PR DESCRIPTION
**Pull request by lorenz**
This is an implementation of https://github.com/google/jsonnet/issues/195 for the Go version since the concerns mentioned in that issue are of no concern in a Go application. It's just a very quick fix done for my own needs, feel free to reject in case you don't want any divergence from the C++ implementation.

### CODE REVIEW

**Comment by lorenz** [comment]
Signed the CLA

**Comment by sparkprime** [comment]
This is great but can you put it in a flag that's off by default and also make it do it in the single file case?

**Comment by lorenz** [comment]
Sure

**Comment by lorenz** [comment]
Made it into an option and added single file support

**Comment by lorenz** [comment]
The failed tests are in the cpp-jsonnet repo, how should this be synchronized? If the PR there goes in before this one, the build is broken and the other way round too.

**Comment by sbarzowski** [comment]
Oh, we're comparing help output directly. Well this is our test mechanism's fault, sorry about that. It's not very important how we go around it, as long as we update both in the timespan of less than few hours. Pehaps later we can move implementation-specific output to implementation repo (it should be just a few lines of changes in the scripts).

**Comment by sparkprime** [comment]
I believe it should be possible to update cpp-jsonnet but not go-jsonnet, and then go-jsonnet will not take that version of cpp-jsonnet until it is updated, so you can do that update at the same time as introducing the change.

**Comment by lorenz** [comment]
Update seems to have broken another assertion (non cmd-related), not sure about that

**Comment by sbarzowski** [comment]
I don't think it has anything to do with this change. It's happened just because of the submodule update. I'll investigate later today.

**Comment by sbarzowski** [comment]
As I thought, it's just the matter of updating stdlib to match C++ updates (there was a bugfix related to escaping there). If you add this commit to the pull request the tests should run fine https://github.com/sbarzowski/go-jsonnet/commit/baff839b5c47ce94c99bc98cc591fb1bd57b3bc5

**Comment by lorenz** [comment]
Looks good now

**Comment by sbarzowski** [comment]
Yes, I'm officially ok with my commit being merged here.

**Comment by sparkprime** [comment]
Thanks

**Comment by alem0lars** [comment]
Is this feature released?

**Comment by sbarzowski** [comment]
Yes

**Pull request merged**
