### PR TITLE
vendor: Add vendoring with dep

### PR DESCRIPTION
**Pull request by dlespiau**
Vendoring helps with reproducible builds and make compiling go-jsonnet easier
as it doesn't rely on having its dependencies in GOPATH.

dep is the current vendoring tool with the most mind share and this commit is
just the result of:

  $ dep init

Fixes: #237

### CODE REVIEW

**Comment by dlespiau** [comment]
Something seems wrong with he Appveyor test. It also fails on master.

```
build started
git clone -q https://github.com/google/go-jsonnet.git C:\projects\go-jsonnet
git fetch -q origin +refs/pull/244/merge:
git checkout -qf FETCH_HEAD
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```

**Comment by sbarzowski** [comment]
Thanks! This would definitely help with the problems people experienced on #239.

I'm not sure how vendor dir would affect people using go-jsonnet as a library, especially if they don't use dep, but happen to depend on the same packages. Do you have any experience with that? We need to have an answer ready.

And eventually I think we should use go modules - at least once they stabilize and become the fully official solution.

Don't worry about appveyor. It was set up once, and caused problems ever since. We probably should either fix it or remove it, so it stops bothering people.

**Comment by dlespiau** [comment]
Yes, indeed! It should help in that case. Next PR could be simplifying the install instructions to a single `go get` command (or it could be a commit on top of this PR).
 
For library users:
- if they use dep, nice! dep should solve the constraints various libraries have and come up with the right version to use.
- if they don't, it's always possible to `rm -rf vendor/`. I would expect other vendoring tools to not look at the `vendor/` directory of dependencies if they haven't been vendored using that same tool, but it has been a very long time since I looked at anything else than `dep`. A nice plus is that, when vendoring their own project with other tools, people can look at the `Gopkg.lock` file to have guidance on the versions that go-jsonnet was tested with.

There's another option: it's possible to commit the Gopkg.toml and Gopkg.lock files and **not** commit the vendor directory. It means people have to run `dep ensure` themselves before building jsonnet, dep ensure will then select the "locked" versions described in the `.lock` file. `go get` will not work though, but I understand some maintainers may prefer not having the `vendor/` directory committed.

Everyone should move to go modules once they are ready :)

**Comment by dlespiau** [comment]
Added a couple of commit on top that result from vendoring dependencies:
- We don't need to `go get github.com/sergi/go-diff/diffmatchpatch` in the CI setup as it's vendored
- We can simplify the installation instructions in the README

**Comment by michaeljs1990** [comment]
Does it make sense to use dep when `go mod` is becoming the lingua franca in the golang ecosystem since 1.11?

**Comment by dlespiau** [comment]
No, not really, time to close this PR!

**Pull request closed without merging**
