### PR TITLE
fix(stdlib): 🐛  manifestJsonEx was escaping HTML

### LINKED ISSUE #423: ManifestJsonEx bug found..
```
"title": "Availability (30d) > 99.000",
"title": "Availability (30d) \u003e 99.000",
```

I just discovered this when running the new go-jsonnet against kube-prometheus

@sbarzowski sorry!

### PR DESCRIPTION
**Pull request by ghostsquad**
minimal repo: https://play.golang.org/p/GQBNMe6k_nm

https://stackoverflow.com/questions/28595664/how-to-stop-json-marshal-from-escaping-and\nminimal 

fix proof: https://play.golang.org/p/SJM3KLkYW-

resolves #423

### CODE REVIEW

**Comment by sbarzowski** [comment]
Could you also add a small regression test to make sure we don't run into this again?

**Comment by sbarzowski** [comment]
FYI it's enough to drop a file in testdata/ and run `go test -update` to generate the golden.

**Comment by wmcnamee-tunein** [comment]
@sbarzowski ready for review

**Comment by sbarzowski** [comment]
Thanks fot catching it so quickly.

**Comment by ghostsquad** [comment]
OH! I was wondering how to do that... maybe a note in the readme on how to generate golden's would be useful.

**Pull request merged**
