### PR TITLE
Fix bug messing up newlines

### PR DESCRIPTION
**Pull request by sbarzowski**
When the lexer backed up, no matter from what character it went
to the previous line.

### CODE REVIEW

**Comment by sbarzowski** [comment]
ping @lwander, @sparkprime

**Comment by sparkprime** [comment]
I can't see what you changed here except refactoring to pull the 3 vars into a struct.  Somewhere in there, I'm sure there's a logic change too but I can't find it

**Comment by lwander** [comment]
Backup used to restore the prior line number, now it just restores the prior "pos" struct: https://github.com/google/go-jsonnet/pull/19/files#diff-afa30dddc22eee32cb8f633eef30e7f2L305

**Comment by sparkprime** [comment]
It used to restore the lineNumber, lineStart and byte pos, and now it does all 3 of those via struct assignment.

**Comment by sparkprime** [comment]
Is this the change: https://github.com/google/go-jsonnet/pull/19/files#diff-afa30dddc22eee32cb8f633eef30e7f2R269

**Comment by lwander** [comment]
You pointed out a logic change, but I don't think that was the intent.

Notice how before prevLineNumber was only being set on advancing over newlines: https://github.com/google/go-jsonnet/pull/19/files#diff-afa30dddc22eee32cb8f633eef30e7f2L279

In conjunction with what I pointed out before, it would always restore lineNumber to the last line. 

Another description of the bug would be "the prior token's line number was only incremented on newlines, but restored everytime a token was backed up"

**Comment by sbarzowski** [comment]
Example string "a\nb".
And imagine the lexing goes like this (these are not real rules, just for seeing what next and backup does):
<op> <char> <line> <byteNo>
next "a" 1, 2
next "\n" 2, 2,
next "b" 2, 3
back "b" 1, 2 <--- do you see the problem?
next "b" 1, 3

**Comment by sparkprime** [comment]
Yeah so backup() wasn't working before, but only because next() wasn't maintaining the counters correctly.

**Comment by sparkprime** [comment]
LGTM

**Pull request merged**
