### PR TITLE
Expose "unparse", FormatNode and RawAST

### PR DESCRIPTION
**Pull request by tomwilkie**
(Opening this for discussion, see #389) 

I've build a little tool that does some modifications to jsonnet files (updating docker image versions in them), and wanted to use the pretty-printing code to write out the modified AST.  

This is a minimal set of changes that allow me to do that.

### CODE REVIEW

**Comment by sbarzowski** [comment]
Looks good. I'm happy to go forward with this. Don't worry about CI failure, it's unrelated and not blocking, I'm going to fix this in a separate CL.

**Comment by peterbueschel** [comment]
Hi guys,
exposing esp. the "SnippetToRawAST" would be great also for me, to be able to get also the comments from the code (as I am currently trying to write a doc generator).

**Comment by charleskorn** [comment]
@sbarzowski any chance you could take another look at this now that @tomwilkie has marked it as ready for review? If it's easier, I could open a replacement PR with these changes rebased on `master`.

**Comment by sbarzowski** [comment]
Sorry for the slow reply.

I'm happy with exposing this, but yeah, we need to rebase.

**Comment by charleskorn** [comment]
> I'm happy with exposing this, but yeah, we need to rebase.

I've opened #710, which contains identical changes but is rebased on `master`.

**Comment by charleskorn** [comment]
#710 has been merged, so this PR can be closed.

**Comment by sparkprime** [comment]
Thanks for the original PR Tom, hope you're well!

**Comment by tomwilkie** [comment]
Thank you @charleskorn! 👋 @sparkprime, doing well - yourself?

**Pull request closed without merging**
